sudo: required
services:
  - docker

before_install:
  - docker build -t meridian1234/docker-react -f Dockerfile.dev .

script:
  - docker run CI=true meridian1234/docker-react npm run test -- --coverage